// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJATbIJD0PzqUAQOg0ffYF5o5P7uDfnk',
    appId: '1:642297141355:web:dee9d5f25732c25a21392e',
    messagingSenderId: '642297141355',
    projectId: 'practice-57053',
    authDomain: 'practice-57053.firebaseapp.com',
    storageBucket: 'practice-57053.firebasestorage.app',
    measurementId: 'G-SEP5QXE1EY',
     databaseURL:"https://practice-57053-default-rtdb.firebaseio.com"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoxN6x8kmzAuyPk6l3kFIlFzR0H2eD0Q0',
    appId: '1:642297141355:android:e3c834c6d8d71c8721392e',
    messagingSenderId: '642297141355',
    projectId: 'practice-57053',
    storageBucket: 'practice-57053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQL3Zhoj0fQX64EyJm2cZpOe1_JTG1Hc',
    appId: '1:642297141355:ios:31848faae3515e2a21392e',
    messagingSenderId: '642297141355',
    projectId: 'practice-57053',
    storageBucket: 'practice-57053.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );
}
